# server/Dockerfile
FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y unzip <% if (dbms !== 'sqlite') { %>\<% }%>
<% if (dbms === 'pgsql') { -%>
    libpq-dev \
    && docker-php-ext-install pdo_pgsql
<% } else if (dbms === 'mysql' || dbms === 'mariadb') {-%>
    default-mysql-client \
    && docker-php-ext-install pdo_mysql
<% }-%>

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set the working directory
WORKDIR /var/www/html

# Copy application files
COPY --chown=www-data:www-data ./server .
COPY --chown=www-data:www-data ./docker/server/.env ./.env

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader
RUN composer require fakerphp/faker --dev

# Configure permissions
RUN touch storage/logs/laravel.log && chown www-data:www-data storage/logs/laravel.log && chmod -R 775 storage bootstrap/cache

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Run PHP-FPM
# CMD ["sh", "-c", "php artisan migrate && php-fpm"]
CMD ["sh", "-c", "php artisan migrate<%- (searchEngine === 'elastic') ? ' && php artisan elastic:migrate' : '' %> && php-fpm"]