# server/Dockerfile
FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y unzip \
<% if (dbms === 'pgsql') { -%>
    libpq-dev \
    && docker-php-ext-install pdo_pgsql
<% } else if (dbms === 'mysql' || dbms === 'mariadb') {-%>
    default-mysql-client \
    && docker-php-ext-install pdo_mysql
<% }-%>

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set the working directory
WORKDIR /var/www/html

# Copy application files
COPY ./server .
COPY ./docker/server/.env ./.env

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader
RUN composer require fakerphp/faker --dev

# Configure permissions
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html \
    && chmod -R 775 /var/www/html/storage \
    && chmod -R 775 /var/www/html/bootstrap/cache

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Run PHP-FPM
CMD ["sh", "-c", "php artisan migrate && php-fpm"]
# CMD ["sh", "-c", "php artisan migrate:fresh --seed && php-fpm"]