FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y unzip

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set the working directory
WORKDIR /var/www/html

# Copy application files
COPY ./server .

# Install PHP dependencies
RUN composer install --no-dev --optimize-autoloader
# RUN composer require fakerphp/faker --dev

# Configure permissions
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html \
    && chmod -R 775 /var/www/html/storage \
    && chmod -R 775 /var/www/html/bootstrap/cache

# Migrate & seed
RUN php artisan migrate
# !!DANGER!! RUN php artisan migrate:fresh --seed !!DANGER!!

# Expose port 9000 for PHP-FPM
EXPOSE 9000

# Run PHP-FPM
CMD ["php-fpm"]