# nginx/Dockerfile
FROM node:20-alpine as builder

WORKDIR /app

COPY ./client .
RUN npm i
RUN npm run build

# Stage finale - nginx per servire i file statici
FROM nginx:alpine as production

# Copia i file build
COPY --from=builder /app/dist /var/www/html
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf